name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Information
      run: |
        echo "Debugging SSH connection"
        echo "DO_HOST is set: ${{ secrets.DO_HOST != '' }}"
        echo "DO_USERNAME is set: ${{ secrets.DO_USERNAME != '' }}"
        echo "DO_SSH_PRIVATE_KEY is set: ${{ secrets.DO_SSH_PRIVATE_KEY != '' }}"
        
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          cd ~/fullstack-blogging-app
          git pull origin main
          
          # Backend
          cd backend
          npm install
          npm start  # If you have a build step for the backend
          
          # Frontend
          cd ../frontend
          npm install
          npm run build
          
          # Restart services
          cd ..
          pm2 restart backend
          pm2 restart frontend  # If you're serving the frontend with Node.js
